### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by leondarkmodeon** [Mr-Abood/TikTok-Encryption#4]
hi!
https://cebbb826-fe89-4212-95c3-1fdb623605fb-00-2g826w2ezsw96.asia-b.replit.dev/sign
It doesn't work with this domain.

answer:
The Repl is currently not running.
"https://replit.com/replid/cebbb826-fe89-4212-95c3-1fdb623605fb?from=replit.dev" View on replit.com

**Comment by leondarkmodeon** [comment]
Hello again.
Response:
Expected X-Requested-With header.

**Comment by lkxoayh** [comment]
same

**Comment by leondarkmodeon** [comment]
Hello, can you please tell me if this will work?
